// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SignalMessages.proto

public final class SignalMessages {
  private SignalMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SignalLevelOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 signalID = 1 [default = 1];
    /**
     * <code>required int32 signalID = 1 [default = 1];</code>
     */
    boolean hasSignalID();
    /**
     * <code>required int32 signalID = 1 [default = 1];</code>
     */
    int getSignalID();

    // required float signalLevel = 2 [default = 0];
    /**
     * <code>required float signalLevel = 2 [default = 0];</code>
     *
     * <pre>
     *required int32 bufferSize = 3 [default=64];
     * </pre>
     */
    boolean hasSignalLevel();
    /**
     * <code>required float signalLevel = 2 [default = 0];</code>
     *
     * <pre>
     *required int32 bufferSize = 3 [default=64];
     * </pre>
     */
    float getSignalLevel();
  }
  /**
   * Protobuf type {@code SignalLevel}
   */
  public static final class SignalLevel extends
      com.google.protobuf.GeneratedMessage
      implements SignalLevelOrBuilder {
    // Use SignalLevel.newBuilder() to construct.
    private SignalLevel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SignalLevel(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SignalLevel defaultInstance;
    public static SignalLevel getDefaultInstance() {
      return defaultInstance;
    }

    public SignalLevel getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SignalLevel(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              signalID_ = input.readInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              signalLevel_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SignalMessages.internal_static_SignalLevel_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SignalMessages.internal_static_SignalLevel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SignalMessages.SignalLevel.class, SignalMessages.SignalLevel.Builder.class);
    }

    public static com.google.protobuf.Parser<SignalLevel> PARSER =
        new com.google.protobuf.AbstractParser<SignalLevel>() {
      public SignalLevel parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SignalLevel(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SignalLevel> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 signalID = 1 [default = 1];
    public static final int SIGNALID_FIELD_NUMBER = 1;
    private int signalID_;
    /**
     * <code>required int32 signalID = 1 [default = 1];</code>
     */
    public boolean hasSignalID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 signalID = 1 [default = 1];</code>
     */
    public int getSignalID() {
      return signalID_;
    }

    // required float signalLevel = 2 [default = 0];
    public static final int SIGNALLEVEL_FIELD_NUMBER = 2;
    private float signalLevel_;
    /**
     * <code>required float signalLevel = 2 [default = 0];</code>
     *
     * <pre>
     *required int32 bufferSize = 3 [default=64];
     * </pre>
     */
    public boolean hasSignalLevel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float signalLevel = 2 [default = 0];</code>
     *
     * <pre>
     *required int32 bufferSize = 3 [default=64];
     * </pre>
     */
    public float getSignalLevel() {
      return signalLevel_;
    }

    private void initFields() {
      signalID_ = 1;
      signalLevel_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSignalID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSignalLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, signalID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, signalLevel_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, signalID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, signalLevel_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SignalMessages.SignalLevel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SignalMessages.SignalLevel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SignalMessages.SignalLevel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SignalMessages.SignalLevel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SignalMessages.SignalLevel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SignalMessages.SignalLevel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SignalMessages.SignalLevel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SignalMessages.SignalLevel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SignalMessages.SignalLevel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SignalMessages.SignalLevel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SignalMessages.SignalLevel prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SignalLevel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SignalMessages.SignalLevelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SignalMessages.internal_static_SignalLevel_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SignalMessages.internal_static_SignalLevel_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SignalMessages.SignalLevel.class, SignalMessages.SignalLevel.Builder.class);
      }

      // Construct using SignalMessages.SignalLevel.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        signalID_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        signalLevel_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SignalMessages.internal_static_SignalLevel_descriptor;
      }

      public SignalMessages.SignalLevel getDefaultInstanceForType() {
        return SignalMessages.SignalLevel.getDefaultInstance();
      }

      public SignalMessages.SignalLevel build() {
        SignalMessages.SignalLevel result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SignalMessages.SignalLevel buildPartial() {
        SignalMessages.SignalLevel result = new SignalMessages.SignalLevel(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.signalID_ = signalID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.signalLevel_ = signalLevel_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SignalMessages.SignalLevel) {
          return mergeFrom((SignalMessages.SignalLevel)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SignalMessages.SignalLevel other) {
        if (other == SignalMessages.SignalLevel.getDefaultInstance()) return this;
        if (other.hasSignalID()) {
          setSignalID(other.getSignalID());
        }
        if (other.hasSignalLevel()) {
          setSignalLevel(other.getSignalLevel());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSignalID()) {
          
          return false;
        }
        if (!hasSignalLevel()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SignalMessages.SignalLevel parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SignalMessages.SignalLevel) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 signalID = 1 [default = 1];
      private int signalID_ = 1;
      /**
       * <code>required int32 signalID = 1 [default = 1];</code>
       */
      public boolean hasSignalID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 signalID = 1 [default = 1];</code>
       */
      public int getSignalID() {
        return signalID_;
      }
      /**
       * <code>required int32 signalID = 1 [default = 1];</code>
       */
      public Builder setSignalID(int value) {
        bitField0_ |= 0x00000001;
        signalID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 signalID = 1 [default = 1];</code>
       */
      public Builder clearSignalID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        signalID_ = 1;
        onChanged();
        return this;
      }

      // required float signalLevel = 2 [default = 0];
      private float signalLevel_ ;
      /**
       * <code>required float signalLevel = 2 [default = 0];</code>
       *
       * <pre>
       *required int32 bufferSize = 3 [default=64];
       * </pre>
       */
      public boolean hasSignalLevel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float signalLevel = 2 [default = 0];</code>
       *
       * <pre>
       *required int32 bufferSize = 3 [default=64];
       * </pre>
       */
      public float getSignalLevel() {
        return signalLevel_;
      }
      /**
       * <code>required float signalLevel = 2 [default = 0];</code>
       *
       * <pre>
       *required int32 bufferSize = 3 [default=64];
       * </pre>
       */
      public Builder setSignalLevel(float value) {
        bitField0_ |= 0x00000002;
        signalLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float signalLevel = 2 [default = 0];</code>
       *
       * <pre>
       *required int32 bufferSize = 3 [default=64];
       * </pre>
       */
      public Builder clearSignalLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        signalLevel_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SignalLevel)
    }

    static {
      defaultInstance = new SignalLevel(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SignalLevel)
  }

  public interface ImpulseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 signalID = 1 [default = 1];
    /**
     * <code>required int32 signalID = 1 [default = 1];</code>
     */
    boolean hasSignalID();
    /**
     * <code>required int32 signalID = 1 [default = 1];</code>
     */
    int getSignalID();
  }
  /**
   * Protobuf type {@code Impulse}
   */
  public static final class Impulse extends
      com.google.protobuf.GeneratedMessage
      implements ImpulseOrBuilder {
    // Use Impulse.newBuilder() to construct.
    private Impulse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Impulse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Impulse defaultInstance;
    public static Impulse getDefaultInstance() {
      return defaultInstance;
    }

    public Impulse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Impulse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              signalID_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SignalMessages.internal_static_Impulse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SignalMessages.internal_static_Impulse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SignalMessages.Impulse.class, SignalMessages.Impulse.Builder.class);
    }

    public static com.google.protobuf.Parser<Impulse> PARSER =
        new com.google.protobuf.AbstractParser<Impulse>() {
      public Impulse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Impulse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Impulse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 signalID = 1 [default = 1];
    public static final int SIGNALID_FIELD_NUMBER = 1;
    private int signalID_;
    /**
     * <code>required int32 signalID = 1 [default = 1];</code>
     */
    public boolean hasSignalID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 signalID = 1 [default = 1];</code>
     */
    public int getSignalID() {
      return signalID_;
    }

    private void initFields() {
      signalID_ = 1;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSignalID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, signalID_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, signalID_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SignalMessages.Impulse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SignalMessages.Impulse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SignalMessages.Impulse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SignalMessages.Impulse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SignalMessages.Impulse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SignalMessages.Impulse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SignalMessages.Impulse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SignalMessages.Impulse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SignalMessages.Impulse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SignalMessages.Impulse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SignalMessages.Impulse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Impulse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SignalMessages.ImpulseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SignalMessages.internal_static_Impulse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SignalMessages.internal_static_Impulse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SignalMessages.Impulse.class, SignalMessages.Impulse.Builder.class);
      }

      // Construct using SignalMessages.Impulse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        signalID_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SignalMessages.internal_static_Impulse_descriptor;
      }

      public SignalMessages.Impulse getDefaultInstanceForType() {
        return SignalMessages.Impulse.getDefaultInstance();
      }

      public SignalMessages.Impulse build() {
        SignalMessages.Impulse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SignalMessages.Impulse buildPartial() {
        SignalMessages.Impulse result = new SignalMessages.Impulse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.signalID_ = signalID_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SignalMessages.Impulse) {
          return mergeFrom((SignalMessages.Impulse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SignalMessages.Impulse other) {
        if (other == SignalMessages.Impulse.getDefaultInstance()) return this;
        if (other.hasSignalID()) {
          setSignalID(other.getSignalID());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSignalID()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SignalMessages.Impulse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SignalMessages.Impulse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 signalID = 1 [default = 1];
      private int signalID_ = 1;
      /**
       * <code>required int32 signalID = 1 [default = 1];</code>
       */
      public boolean hasSignalID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 signalID = 1 [default = 1];</code>
       */
      public int getSignalID() {
        return signalID_;
      }
      /**
       * <code>required int32 signalID = 1 [default = 1];</code>
       */
      public Builder setSignalID(int value) {
        bitField0_ |= 0x00000001;
        signalID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 signalID = 1 [default = 1];</code>
       */
      public Builder clearSignalID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        signalID_ = 1;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Impulse)
    }

    static {
      defaultInstance = new Impulse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Impulse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SignalLevel_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SignalLevel_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Impulse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Impulse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024SignalMessages.proto\":\n\013SignalLevel\022\023\n" +
      "\010signalID\030\001 \002(\005:\0011\022\026\n\013signalLevel\030\002 \002(\002:" +
      "\0010\"\036\n\007Impulse\022\023\n\010signalID\030\001 \002(\005:\0011B\020B\016Si" +
      "gnalMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_SignalLevel_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_SignalLevel_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_SignalLevel_descriptor,
              new java.lang.String[] { "SignalID", "SignalLevel", });
          internal_static_Impulse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Impulse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Impulse_descriptor,
              new java.lang.String[] { "SignalID", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
